### ISSUE TITLE
anyone had this problem before, when you make c, it telling you vspec does not have load attribute ?

### ISSUE THREAD

**Issue by zylinux** [COVESA/vss-tools#176]
vehicle_signal_specification$ make c
(cd ./vss-tools/contrib/vspec2c/; make )
make[1]: Entering directory '/home/mzhang73/tmp/vehicle_signal_specification/vss-tools/contrib/vspec2c'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/mzhang73/tmp/vehicle_signal_specification/vss-tools/contrib/vspec2c'
PYTHONPATH=./vss-tools ./vss-tools/contrib/vspec2c.py -I ./spec ./spec/VehicleSignalSpecification.vspec vss_rel_$(cat VERSION).h vss_rel_$(cat VERSION)_macro.h
Traceback (most recent call last):
  File "./vss-tools/contrib/vspec2c.py", line 293, in <module>
    tree = vspec.load(args[0], include_dirs)
AttributeError: module 'vspec' has no attribute 'load'
Makefile:62: recipe for target 'c' failed
make: *** [c] Error 1

@erikbosch

**Comment by zylinux** [comment]
if Contrib (Obsolete, no longer functional), is there any alternative way would do any c++ or c header etc

**Comment by erikbosch** [comment]
The `vspec2c` is as you found out obsolete, no-one has yet had any time or interest to keep it up to date. Adapting it so it use `load_tree` instead of `load` is likely the simple part, there might be other parts that require more work like support for array types.

The only other vss tool related to c is [vss2binary](https://github.com/COVESA/vss-tools/blob/master/binary/README.md)

**Comment by erikbosch** [comment]
Closing this one. Question answered. If anyone has interest in fixing vspec2c it would be welcome.
