### ISSUE TITLE
DDS export of vss generated IDL fails

### ISSUE THREAD

**Issue by AkhilTThomas** [COVESA/vss-tools#185]
Hi,

I'm trying to generate the python idl types for the vss data points.

IDL creation
``python vspec2ddsidl.py -I ..\spec ..\spec\VehicleSignalSpecification.vspec vss.idl``

IDL to python conversion
``/opt/cycloneDDS/bin/idlc  -l py vss.idl``

Error:
``
/tmp/dds/vss.idl:597:27: Declaration 'UNKNOWN' collides with earlier an declaration of 'UNKNOWN'
/tmp/dds/vss.idl:693: fatal error: File write error
    };
1 error in preprocessor.
``

The vss IDL generated enums with same value:

line 597 ``enum AspirationTypeValues{UNKNOWN,NATURAL,SUPERCHARGER,TURBOCHARGER};``

line 535 ``enum ConfigurationValues{UNKNOWN,STRAIGHT,V,BOXER,W,ROTARY,RADIAL,SQUARE,H,U,OPPOSED,X};``

vss = _release/3.0_
vss-tools =_release/3.0_
idlc (Eclipse Cyclone DDS)  = _0.10.0_

Is this an error in the VSS or the IDLc from cyclonedds ?

**Comment by SebastianSchildt** [comment]
@zam1kor  can you check? I am not sure, does DDS IDL not allow to choose same symbolic names in different enums (seems strange). Does FastDDS IDL compiler behave differently?

If we are doing something illegal in DDS-IDL we need to rethink that part of the mapping, otherwise maybe open a report upstream in Cyclone.

**Comment by AkhilTThomas** [comment]
FastDDS throws even more errors!

interesting ones:
``vss.idl:5122:0: error: Illegal identifier: Switch is a keyword, use escape character if you want to use it as identifier (_Switch)
``
``vss.idl:671:0: error: Illegal identifier: MAP is a keyword, use escape character if you want to use it as identifier (_MAP)
``
https://github.com/COVESA/vehicle_signal_specification/blob/2b24d0d9ac6b2d357e1d97ca3064cc2ca5bfa089/spec/Cabin/SingleSliderSwitch.vspec

Switch:
  datatype: string
  type: actuator
  allowed: ['INACTIVE', 'CLOSE', 'OPEN', 'ONE_SHOT_CLOSE', 'ONE_SHOT_OPEN']
  description: Switch controlling sliding action such as window, sunroof, or blind.

I've attached the errors as well as the idl generated
[vss.txt](https://github.com/COVESA/vss-tools/files/9407825/vss.txt)

[error.txt](https://github.com/COVESA/vss-tools/files/9406936/error.txt)

**Comment by AkhilTThomas** [comment]
Adding more info:

Taken from ([IDL Definition](https://www.omg.org/spec/IDL/4.2/PDF#page=115))

> Enumeration value names are introduced into the enclosing scope and then are treated like any other declaration in that
scope. For example:
interface A {
enum E { E1, E2, E3 }; // line 1
enum BadE { E3, E4, E5 }; // Error: E3 is already introduced...
// ...into the A scope in line 1 above
};
interface C {
enum AnotherE { E1, E2, E3 };
};
interface D : C, A {
union U switch (E) {
case A::E1 : boolean b; // OK.
case E2 : long l; // Error: E2 is ambiguous (notwithstanding...
// ... the switch type specification)
};

In VSS the enum value UNKNOWN is redefined within the same module scope.
Refer module [CombustionEngine](https://github.com/COVESA/vehicle_signal_specification/blob/02b1d6eb0b081cd3cc2814389a8a920c0258f2f5/spec/Powertrain/CombustionEngine.vspec)

Does this mean that the VSS name would get changed or the IDL enums generated gets a prefix of the scope?

**Comment by erikbosch** [comment]
> Does this mean that the VSS name would get changed or the IDL enums generated gets a prefix of the scope?

My view is that we shall try as far as possible try to avoid restricting names and identifiers in VSS. We already have some general rules/recommendations in https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/allowed/#recommendation-on-string-values and https://covesa.github.io/vehicle_signal_specification/rule_set/basics/#naming-conventions but they do not consider language-specific restrictions. I could possibly think of introducing a set of reserved keywords in VSS, but then they should rather be based on keywords used in VSS rather than in target languages. For example, I have no problems if VSS would reject signals called `uint8` or `branch`,  but `Switch` is not a VSS keyword and shall thus be accepted in VSS.

So I suggest that we do not change the VSS identifiers, but rather implement support to handle the restrictions, like replacing `MAP` with `_MAP` and possibly put all enums when generating DDSIDL in separate modules to avoid name clashes.

**Comment by SebastianSchildt** [comment]
Agree with Erik, although I am not a DDS guy.

For enums, I think prefixing it somehow with the Path is easy (however, will be long: Consider seats: It would need to include the whole instantiated path including Row/Column, otherwise it clashes again)

with the `MAP`vs `_MAP` thing, the problem is I am not sure if the underscore is visible within the generated code output, and whether it is somehow the canonical DDS-IDL way to do, or just a fastDDS convention (I do see a bit of a challenge to solve this "generally" for all VSS models)

**Comment by AkhilTThomas** [comment]
#186 I have updated the module scoping for enums and a keyword checker prefxing _ on keyword detection. With these changes i was able to convert the generated idl in cyclonedds.

**Comment by AkhilTThomas** [comment]
Fixed with #186
