### ISSUE TITLE
AMM Idea: Overlays -removal of nodes

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vss-tools#194]
Idea collected at AMM. It would be valuable to be able to specify that a node/branch shall be removed by an overlay

**Comment by ppb2020** [comment]
There is some inconsistency in the documentation on how to refer to components of a node such as "datatype", "unit", etc. In some cases, these are referred to as "members" and as "elements" in other cases. Perhaps this should be cleaned up. For the purposes of this discussion, I will be using "element".

Removing nodes by deleting them from VSPEC files has licensing implications as it requires the person or company making the deletions to publish the updated VSPEC files. A mechanism that allows for the deletion or removal to be done through overlays would remove this requirement as overlays were specifically designed to support changing the signal catalog.

A possible approach to support deletion is to add a formal element to the definition of nodes that indicates whether the node is active or not. The name of the element would reflect the state of the node. Something like active, deleted, etc. For the purposes of this discussion, let's call it "active". This element could be defined as part of the VSS or introduced through overlays.

Early investigation suggested this "active" element would be a boolean value that could be set through overlays to indicate that the node is inactive. In this manner, post-overlay application tooling (such as the vss-tools that convert VSPECs to other formats) could remove the nodes marked as inactive and only leave active nodes. A branch marked as inactive would cause all nodes below this branch to be considered inactive, whatever their "active" element setting would be. This would support very simple deletion of irrelevant nodes, such as combustion engine nodes for EVs. In this case, the element could also be removed from each node in the catalog that is used at runtime, reducing memory and file usage.

Further investigation revealed that deletion of nodes through tooling may in some cases be premature. That is, in the interest of supporting dynamically inactivating or activating nodes at runtime, it would be preferable for some inactive nodes to not actually be deleted, but remain present in the runtime, such that they can be dynamically activated (hence my choice of "active" as the name of the element instead of "deleted"). For example, this would facilitate the support of "pay-as-you-go" vehicle features for which signals could come and go dynamically at runtime. This adds capability at the cost of more memory or file system usage.

Eventually, a combination of deletion and activation may be needed or useful. In that case, perhaps a better name for the new element would be "status", with the following values: "active", "inactive", "deleted". With this approach, "deleted" signals could be removed by tooling, while still allowing support for dynamic activation or inactivation at runtime. This would achieve some memory and file system savings, while providing unique functionality for dynamic activation of vehicle features.

The new element could also be introduced progressively, by assuming a value of "active" if the element is not present in the VSPEC or overlay for any node.

**Comment by nwesem** [comment]
Was added in this PR https://github.com/COVESA/vss-tools/pull/348

**Comment by erikbosch** [comment]
Closing it, thanks for your contribution
