### ISSUE TITLE
Add py.typed to support mypy types verification

### ISSUE THREAD

**Issue by kse3hi** [COVESA/vss-tools#208]
More details:
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

**Comment by erikbosch** [comment]
I like the idea, but I think that we should discuss how our mypy ambition level should look like. If you just run `mypy .` in vss-tools today you get a quite long list of errors. Some seems to be very easy and reasonable to fix, others maybe not worth the effort or simply not doable by us.

I assume it would be a good idea to run mypy as part of our [continuous integration](https://github.com/COVESA/vss-tools/blob/master/.github/workflows/buildcheck.yml), but if so with which parameters? I am thinking if we already now should start running mypy with parameters that represents wanted checks , but for now mark the run as "successful" even if errors are reported. Possibly something like below? Then later, when everything that we want to fix has been fixed we can change so that the build fails if errors are reported. 


```
      - name: Run mypy.
        run: |
          python -m pip --quiet --no-input install --upgrade mypy
          cd ${{ env.VSS_TOOLS_PATH }}
          mypy *.py vspec tests contrib ||
            echo "::warning title=mypy::Errors reported"
```

**Comment by kse3hi** [comment]
Hi @erikbosch ,

you are talking about your internal errors - that my advice of course to analyze fix/suppress depends on analyze.
When we are using your product as our external component, we have at least one warning: mypy doesn't see your defined types. PEP to properly maintain it: https://peps.python.org/pep-0561/ 

We don't need any workarounds (e.g. we can just suppress this warning), but our approach to fix it properly.
Therefore I was introduce this fix.

**Comment by erikbosch** [comment]
PRs merged closing this one
