### ISSUE TITLE
Alternative Python tooling

### ISSUE THREAD

**Issue by rfrowe** [COVESA/vss-tools#31]
Hello, just wanted to let you all know about an alternative Python tooling I've been working on. It's designed to read the JSONified specification format and provide an easy-to-use interface for Python developers to use VSS in their code. Newly open sourced [here](https://github.com/XevoInc/vss)!

**Comment by gunnarx** [comment]
Of course nice to see adoption of the technology, in open-source code.

Personally I prefer that tools start from the original YAML which is the true source format, but there could be other workflows of course.   So if I understand correctly, your parser requires a conversion to JSON first, so you would run:

`vspec2json` from the `vss-tools` repository, then run this parser on the resulting json?

I see some assumptions you have made that could be useful, but might need to be discussed and documented.  For example:
- Require that string type does not have a unit defined
- There is an assumption that units are spelled in a way that Pint wants them to be spelled(?)
... and I did not see where you limit it to a smaller list of units allowed in VSS (which is done in the current tooling).

Some assumptions are probably correct but ought to be documented then in VSS specification rather than only a de-facto interpretation in an alternative implementation, in my view.

A lot of these checks make sense, but I would appreciate them in vspec.py and not only in an alternative tool. Maybe we can transfer them over?

**Comment by rfrowe** [comment]
> Personally I prefer that tools start from the original YAML which is the true source format

Yeah I understand that. I made the choice for portability's sake. JSON parsers are more standard than YAML and it means I can go to the releases page, download a single artifact, and run my tooling with that. Perhaps I could parse the original YAML but still satisfy my desire with a tool which processes the spec tree into one YAML by inlining inclusions.

> So if I understand correctly, your parser requires a conversion to JSON first

Yes, in practice I just use the released JSON from the documentation site. However, if I need to add private signal branches I would have to generate JSON as you said.

> Require that string type does not have a unit defined

I think a rather reasonable assumption, born of the fact that Pint cannot handle non-numeric quantities. I think the only case where a string would have a unit is if it were a numeric literal string, in which case it should probably be parsed to a numeric type before it interacts with VSS anyway.

> There is an assumption that units are spelled in a way that Pint wants them to be spelled

An assumption that definitely hasn't bit me (see issues 206, 217, 218, 231). Pint is a great library that allows for super simple unit conversion. For the most part, it is extremely configurable. As you can see [here](https://github.com/XevoInc/vss/blob/master/vss/__init__.py#L22), I use the default Pint unit registry with some additional definitions. In theory, one could use a custom unit registry which is just the units which VSS supports. It does have some limitations, for example `%` cannot be a valid unit and `percent` must be used instead or the fact that. `^` are mandatory for powers. For the most part, Pint follows well accepted standards for unit naming conventions so having VSS's units match Pint's is equivalent to best practice.

> and I did not see where you limit it to a smaller list of units allowed in VSS

Since pint has such broad unit support, I don't enforce that units are VSS-supported which technically means valid VSS JSON is only a subset of the format I support. Could be solved by having pint enforce this itself via a custom unit registry definition.

> A lot of these checks make sense, but I would appreciate them in vspec.py and not only in an alternative tool. Maybe we can transfer them over?

I think that sounds like a great idea. My tooling seems to do a good enough job detecting irregularities.

**Comment by gunnarx** [comment]
>>    Personally I prefer that tools start from the original YAML which is the true source format

> Yeah I understand that. I made the choice for portability's sake. JSON parsers are more standard than YAML 
... but YAML is standard enough, and there are enough parsers for every popular language.  Only in the case of javascript implementations would I consider JSON to be an obviously superior choice, since it is natively understandable by a javascript interpreter.

As I understand it we have the `vspec.py` file as a base class to do the parsing, and all other tools can use the data structure it builds.  So depending on that part of vss-tools is usually expected, or if ingesting JSON you would still be dependent on vss-tools because it needs the yaml2json conversion to be done.   So you either put the YAML to JSON conversion as a first step in your program, or the release-management of a VSS catalog of signals would require an official release of JSON side-by-side with the YAML, which is extra work to ensure those are consistent.

You are free to do it this way, I'm just giving the arguments for why I believe it is a better model that each tool that is written independently takes the responsibility to ingest the original source format. That could be done by reusing the vss2json or some other way, but it becomes that project's responsibility. (Or even better, let's improve vss-tools and we might not need to have that many tools with overlapping functionality).

> and it means I can go to the releases page, download a single artifact, and run my tooling with that. 

Not sure I understood you correctly, but if you mean the _VSS_ release page, then see above.  I just checked and I couldn't find that we actually put any JSON file into the releases, at the moment at least?

> Perhaps I could parse the original YAML but still satisfy my desire with a tool which processes the spec tree into one YAML by inlining inclusions.

`vspec.py` would handle the includes for you, as well as the instantiation (which is quite tricky and we recently fixed bugs).  

Ultimately it's your program and therefore up to you if you prefer to do a conversion first, before further processing.  I'm just trying to influence the principles for the main vss-tools repo.

>>    Require that string type does not have a unit defined
> I think a rather reasonable assumption

Yes I agree, it probably is.

> , born of the fact that Pint cannot handle non-numeric quantities. 

It is hopefully a reasonable assumption for its own sake, rather than what Pint supports?

> I think the only case where a string would have a unit is if it were a numeric literal string,

Yes.  I think it's a question to raise to our discussion of the VSS model definition.  I'm not sure if we have fully clarified whether a string can have a unit or not.

> in which case it should probably be parsed to a numeric type before it interacts with VSS anyway.

But how it is used in the end does not remove the fact that the part of the program that reads the file needs to validate the input, including units.  So we should clearly define whether a string can have a unit.

>>    There is an assumption that units are spelled in a way that Pint wants them to be spelled
> An assumption that definitely hasn't bit me (see issues 206, 217, 218, 231). Pint is a great library that allows for super simple unit conversion... 
> [trimmed]

I am aware of what Pint does and it seems like a good library, but see my conclusion at the end.

> ... For the most part, Pint follows well accepted standards for unit naming conventions so having VSS's units match Pint's is equivalent to best practice.

Yeah, that's fair and we probably match it quite well already, but seems like it is worth checking.

>>    and I did not see where you limit it to a smaller list of units allowed in VSS
> Since pint has such broad unit support, I don't enforce that units are VSS-supported which technically means valid VSS JSON is only a subset of the format I support. 

Again, no offense implied, but it seems backwards to rationalize the program behavior and design choices because of what Pint does or does not do.

We have at least decided so far for VSS that there is a selected set of units and there should at least be a warning when atempting to define something using a different unit (even if it's an actual SI unit or other real world unit).

> Could be solved by having pint enforce this itself via a custom unit registry definition.

My opinion: Pint makes sense if you are going to use it for unit conversion calculations and/or accept all possible types of units.
But for checking whether a stated unit in a VSS input is within a selected set of strings (e.g.:  `if unit in list_of_units:`) it seems like overkill, and I would not personally add a package dependency for such a small thing.

>>    A lot of these checks make sense, but I would appreciate them in vspec.py and not only in an alternative tool. Maybe we can transfer them over?
> I think that sounds like a great idea. My tooling seems to do a good enough job detecting irregularities.

(Except that you do not check for a limited set of approved units)  We currently have that limitation -- it seems to be the consensus of the weekly VSS development meeting (you're welcome to join).

So what other irregularities can we identify?  Do you perform a validation of the input file using a schema because it might be a useful addition, maybe.  I kind of believe (but happy to get contrary evidence) that the current parsers and generators do a fairly good job already.  VSS is such a simple format that there isn't that much to do but to check if the key names are valid names, and that datatypes and units are within requirements.  We occasionally have discussions to clarify if a certain thing is mandatory or not in a certain situation, and if the checking can be improved so there might be some minor things, but we need to identify them.

I'd love to go through the other stated goals of your program to see if we can meet them in the easiest possible way:

* You claim it to be type safe -- is there a case of _non_-type safety we can identify in the current vss-tools?

* You also say it has a convenient easy interface for other python programs to use.   The current base classes like `vspec.py` might need improvement in that area, I'm not sure?  Can we identify where we can improve?

Overall it's great to see adoption of the technology, I'm just looking to see if we could shift focus to improving the "official" vss-tools.   There are likely other green field areas (such as new generators?) where you could provide value and programming input.

Do you want to join the weekly calls and be more part of the VSS team?

**Comment by danielwilms** [comment]
Please close @gunnarx, @erikbosch. @rfrowe, if you think it should still be open, please comment on @gunnarx remarks and reopen.

**Comment by rfrowe** [comment]
@danielwilms I have no qualms with the closure of this issue. Unfortunately, shortly before @gunnarx's last message I was moved off this project at Xevo and could not longer contribute time on the clock. Recently, Xevo underwent several rounds of layoffs. I'm no longer with the company and therefore I have no ownership over the referenced tooling repository or its code. I appreciate all of the time you (and others) have put into reviewing my MRs, issues, and hearing my thoughts and opinions on the structure of VSS. You've made an incredible code base and it made my job much easier. I thank you for all of your efforts.
