### ISSUE TITLE
Discussion on Units

### ISSUE THREAD

**Issue by barbieri** [COVESA/vss-tools#91]
# Introduction

The VSS defines [Data Unit Types](https://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/data_unit_types/) based on the [IS -- International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units).

# Demand/Problem
Since the IS is very extensive, not all units are specified and some may be missing and may be added from time to time. See #84, #76

In addition to that, eventually the IS misses units for some data that may be used in a car, until it catches up, they may be required in the VSS.

There are existing mismatch between the documentation and the implementation, see #90.

# Approaches

There are different approaches to allow these:
1. allow units to be registered, converting the `Enum` (immutable) to a registry (mutable) that private branches can populate;
2. define a community process to request new units to be added

# Discussion

Please leave a comment with your point and rationale. These will be discussed in the VSS weekly meeting.

**Core Question:** Should VSS allow for custom/private units or they all must be specified and present in the [vspec/model/constants.py](https://github.com/GENIVI/vss-tools/blob/master/vspec/model/constants.py#L46)?

If to **allow custom/private units**:
- define an API?
- define a file format/structure, so all tools load the extensions? (of course this would use the API)

If they **all must be specified and in the `vspec/model/constants.py`**: define a process documenting the rules (self-check, submission, approval rules)

**Comment by barbieri** [comment]
My position on the matter: they should be all specified in the VSS.

The process could be based on a PR adding the new type to the enumeration and documentation (until it's auto-generated), the proposal should be clear on the usage, the data type should be general and point to [IS](https://en.wikipedia.org/wiki/International_System_of_Units) (preferably) or some other international organization specifying it (IETF...)

Since this will block the users that needs the units, it's advised to state the expected and maximum review time (ie: 1 week average, 2 weeks maximum), otherwise organizations will need to fork this repo and keep their branch for an unknown period of time, that may cause issues for everyone.

**Comment by Floix** [comment]
We have a local branch, where we just introduce units via a yaml file. Basically a meta-model approach. Registration of units would happen during startup of the VSS tools. Is that helpful to seperate specification and usage of units?

**Comment by SebastianSchildt** [comment]
Notwithstanding any discussions what kind of units are "canonical", standardized, or used in the standard catalogue, from a tooling perspective I strongly believe it should be possible to add units via a configuration file (for example some kind of yaml like @Floix  mentioned).

If that is so, I would consider it good design if the units that are part of the standard catalogue, or that are somehow defined to be "in the standard", are also shipped as such a configuration file with the tools.

As a unit (opposed to datataypes) are more like "metadata", I also think adding units to your own private branches/layers does not need to be discouraged, as it is unlikely to break any common tooling building blocks (i.e. this does not break any VISS server)

**Comment by erikbosch** [comment]
Some thoughts after the discussion today. I think it makes sense to separate between "standard types" and "private types". But then we need to have some form of definition of what we mean with that, and how tools should handle them. Below i some thoughts just out of my head. Do not care that much about details, this is quick dirty work :-)  

**"Standard types"**

- Corresponding to the types currently defined in https://github.com/GENIVI/vss-tools/blob/master/vspec/model/constants.py
- Defined and documented by vss-tools (in constants.py and/or in some other file)
- All tools in vss-tools (possibly except tools in `contrib` folder) shall have a well defined handling for each of them. For example know how to convert the unit, if needed, like in vspec2ttl. This means - if a new standard unit is added - it must be verified and documented how each standard tool will handle it.
- Implementations using VSS (e.g. App SDKs) may typically have prepared widgets for the standard types, e.g. a star-widget to present a signal with unit "stars" as "*****" if the value is 5.

**"Private types"**

- Needs to be defined in a separate config file. Possibly using same format as the definitions of the standard types. Calling it csv-file below but it does not need to be csv, could be basically anything.
- The config file format shall preferably support an arbitrary number of columns with information that can be used by various vss-tools in conversions, if any
- All tools in vss-tools (possibly except tools in `contrib` folder) must support a parameter to include a `private_units.csv` file in the generation
- All tools in vss-tools must give an error if a used unit does not exist in either standard types or in the provided csv-file

**Example**

Assume that we would like to use the private types Millibar and Warp-speed in a customer project, and we want to use the vspec2ttl tool. That tool does not just copy units but rather translate them:

```
 DataUnits = {    
    'N.m': URIRef(Namespaces["cdt"]+'ucum'),
    'cm3': URIRef(Namespaces["cdt"]+'volume'),
    'cm^3': URIRef(Namespaces["cdt"]+'volume'),
```

... so if that tool should be able to handle private units it needs some additional information. this could possibly be solved by adding two vspec2ttl-specific columns to the file containing private types, possibly like this:

```
name;ttl_namespace;ttl_type
'Millibar','qudt','PressureOrStressUnit'
'warp','startrek','LinearVelocityUnit'
```
... and updating the vspec2ttl tool so that it uses the provided namespace and type, and gives error if they are not given. Other tools like vspec2csv only need the first column.

**Comment by gunnarx** [comment]
Collecting effects and considerations for decision:

- Do people prefer to edit python program or edit config (text) file.  Is there a difference?
- Python programs packaged and installed with pip or similar -> suggests the program should not be edited.
- A text file could be used by different implementations  (e.g. non Python).  Compared to a python API, e.g. "register_type(...)"
- If a separate file, does it belong to VSS rather than vss-tools.  
- Complexity of program, needs decision on "format of file", loading/parsing file, etc.  I.e. does loading a separate file add "unnecessary" structure?

Consensus after today:  Further investigate separate config file, come back for final decision.

**Comment by oliveirarleo** [comment]
As we talked about in one of our weekly meetings, I here will propose a file format to describe units. In this way, we can discuss, and if we all agree on a format I can go ahead and code the functionality and send it as a PR.

I thought in a file called `config.yaml` that would have an additional configuration for the vss tree that is not bounded to any branch or leaf in particular.
Units will be inside the 'units' branch (giving the flexibility to add more configuration in the future). Follows as children of  `units` the actual units (this makes it easier to iterate over them) and each by itself has a name, description and domain. These attributes will serve as metadata and can help documentation.

Exemple:
`config.yaml`
```YAML
units:
  "mm":
    name: Millimeter
    description: Distance measured in millimeters
    domain: distance
  "km":
    name: Kilometer
    description: Distance measured in Kilometers
    domain: distance
```

**Comment by barbieri** [comment]
I think it may be helpful to restructure with a `domain` branch before the actual unit, this will make it easier to keep it organized (similar things together), reduce 1 line per entry and avoid typos (`domain: Distance` x `domain: distance` x `domain: distances` x `domain: length` x `domain: dstance`...). Also, no need to have the quotes, that's only required if the value may be misunderstood (ie: boolean, number), which shouldn't be the case with units.

```yml
units:
  distance:
    mm:
      name: Millimeter
      description: Distance measured in millimeters
    km:
      name: Kilometer
      description: Distance measured in Kilometers
```

**Comment by SebastianSchildt** [comment]
Still waiting for a PR 🍰 , 
Not convinced  about making "domain" the primary split, as it currently is not a VSS thing. Therfore I prefer having it as an attribute just as in the first example (if it is useful at all, but I assume it might be for vsso). 
When I want to add/hack an extra unit into my local deployment, which "domain" it is should really not be the first thing I need to think about, and I'd like to prevent a discussion which domains are canonical 🙈, so I rather have domain as optional (we can populate it for all default units of course) attribute

**Comment by danielwilms** [comment]
we name it units.yaml for now, as it now suits only the purpose to document units. If more configuration is needed, we rename it.

**Comment by danielwilms** [comment]
solution merged, please close @gunnarx, @erikbosch
